#cloud-config
package_update: true
packages:
  - curl
  - iptables

runcmd:
  - curl -fsSL https://tailscale.com/install.sh | sh
  - sysctl -w net.ipv4.ip_forward=1
  - tailscale up \
      --authkey=${tailscale_auth_key} \
      --advertise-routes=10.10.1.0/24 \
      --accept-dns=false
